import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import process from 'node:process';
import { spawnSync } from 'node:child_process';

const repo=path.resolve(process.argv[2]??'.');const taskRoot=path.join(repo,'task');const sqlite=process.env.SQLITE_BIN;const assert=(value,message)=>{if(!value)throw new Error(message);};assert(sqlite,'SQLITE_BIN is required');
const run=(command,args,options={})=>{const result=spawnSync(command,args,{encoding:'utf8',windowsHide:true,timeout:180000,...options});if(result.error)throw result.error;return result;};
function extract(archive,dest){const result=run('pwsh.exe',['-NoProfile','-NonInteractive','-Command','Expand-Archive -LiteralPath $env:SOURCE_ZIP -DestinationPath $env:DEST_DIR -Force'],{env:{...process.env,SOURCE_ZIP:archive,DEST_DIR:dest}});assert(result.status===0,result.stderr||result.stdout);}
async function files(base,current=base){const out=[];for(const entry of await fs.readdir(current,{withFileTypes:true})){const full=path.join(current,entry.name);if(entry.isDirectory())out.push(...await files(base,full));else out.push(path.relative(base,full).split(path.sep).join('/'));}return out.sort();}
async function digestTree(base){const hash=crypto.createHash('sha256');for(const rel of await files(base))hash.update(rel).update('\0').update(await fs.readFile(path.join(base,...rel.split('/')))).update('\0');return hash.digest('hex');}
function execute(inputRoot){return run(process.execPath,['tools/run-task.mjs'],{cwd:inputRoot,env:{...process.env,SQLITE_BIN:sqlite}});}
function normalizeDump(text){return text.split(/\r?\n/).filter(line=>line&&!line.startsWith('PRAGMA foreign_keys=OFF;')).join('\n');}
async function compare(actual,expected){const actualFiles=await files(actual),expectedFiles=await files(expected);assert(JSON.stringify(actualFiles)===JSON.stringify(expectedFiles),'Reference file tree differs');for(const rel of expectedFiles){const a=path.join(actual,...rel.split('/')),e=path.join(expected,...rel.split('/'));if(rel.endsWith('.db')){const ad=run(sqlite,[a,'.dump']);const ed=run(sqlite,[e,'.dump']);assert(ad.status===0&&ed.status===0,ad.stderr||ed.stderr);assert(normalizeDump(ad.stdout)===normalizeDump(ed.stdout),`Reference database differs:${rel}`);}else if(rel.endsWith('.csv')){const actualRows=parseCsv(await fs.readFile(a,'utf8'));const expectedRows=parseCsv(await fs.readFile(e,'utf8'));assert(JSON.stringify(actualRows)===JSON.stringify(expectedRows),`Reference CSV differs:${rel}`);}else assert((await fs.readFile(a)).equals(await fs.readFile(e)),`Reference file differs:${rel}`);}}
async function prepare(label,solved=true){const base=await fs.mkdtemp(path.join(os.tmpdir(),`客服 结算 ${label} `));const input=path.join(base,'input'),reference=path.join(base,'reference');await fs.mkdir(input);await fs.mkdir(reference);extract(path.join(taskRoot,'输入数据包.zip'),input);extract(path.join(taskRoot,'reference.zip'),reference);const inputRoot=path.join(input,'input_data');if(solved)await fs.copyFile(path.join(reference,'output','sql','rebuild_sla.sql'),path.join(inputRoot,'starter','rebuild_sla.sql'));return{base,inputRoot,referenceOutput:path.join(reference,'output'),output:path.join(input,'output')};}
function parseCsv(text){const rows=[];let row=[],field='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'&&text[i+1]==='"'){field+='"';i++;}else if(c==='"')quoted=false;else field+=c;}else if(c==='"')quoted=true;else if(c===','){row.push(field);field='';}else if(c==='\n'){row.push(field.replace(/\r$/,''));if(row.some(v=>v!==''))rows.push(row);row=[];field='';}else field+=c;}if(field||row.length){row.push(field);rows.push(row);}const [head,...body]=rows;return body.map(values=>Object.fromEntries(head.map((key,i)=>[key,values[i]??''])));}

const clean=[];let baseline='';
for(const label of ['中文 空格 目录一','中文 空格 目录二']){const room=await prepare(label);const before=await digestTree(room.inputRoot);const result=execute(room.inputRoot);assert(result.status===0,`${label} failed:${result.stderr||result.stdout}`);await compare(room.output,room.referenceOutput);const now=await digestTree(room.output);if(!baseline)baseline=now;assert(await digestTree(room.inputRoot)===before,`${label} input changed`);clean.push({directory_label:label,process_runs:1,input_unchanged:true,reference_full_match:true,output_digest:now});await fs.rm(room.base,{recursive:true,force:true});}

const mutation=await prepare('有效变化');const calendarPath=path.join(mutation.inputRoot,'business_calendar.json');const calendar=JSON.parse(await fs.readFile(calendarPath,'utf8'));const priorP2=calendar.sla_minutes.P2;calendar.sla_minutes.P2=960;await fs.writeFile(calendarPath,JSON.stringify(calendar,null,2)+'\n');const changed=execute(mutation.inputRoot);assert(changed.status===0,changed.stderr||changed.stdout);const slaRows=parseCsv(await fs.readFile(path.join(mutation.output,'reports','sla_clock.csv'),'utf8'));const queueRows=parseCsv(await fs.readFile(path.join(mutation.output,'reports','breach_queue.csv'),'utf8'));assert(slaRows.find(row=>row.ticket_id==='T-1004')?.sla_state==='within_sla','P2 contract change did not update SLA state');assert(queueRows.length===1&&queueRows[0].ticket_id==='T-1005'&&queueRows[0].queue_rank==='1','P2 contract change did not update queue');assert(await digestTree(mutation.output)!==baseline,'valid calendar change did not change business output');await fs.rm(mutation.base,{recursive:true,force:true});

const missing=await prepare('缺少日历');await fs.unlink(path.join(missing.inputRoot,'business_calendar.json'));const missingResult=execute(missing.inputRoot);assert(missingResult.status!==0&&!(await fs.stat(missing.output).catch(()=>null)),'missing calendar left output');await fs.rm(missing.base,{recursive:true,force:true});
const unfinished=await prepare('未完成SQL',false);const unfinishedResult=execute(unfinished.inputRoot);assert(unfinishedResult.status!==0&&!(await fs.stat(unfinished.output).catch(()=>null)),'unfinished SQL left output');await fs.rm(unfinished.base,{recursive:true,force:true});

const crlf=await prepare('CRLF导入');const crlfResult=execute(crlf.inputRoot);assert(crlfResult.status===0,crlfResult.stderr||crlfResult.stdout);const importDb=path.join(crlf.base,'crlf-import.db');const imports=[['sla_clock.csv',10,7],['pause_interval_audit.csv',7,3],['breach_queue.csv',6,2]];const imported=[];for(const [name,columns,records] of imports){const source=await fs.readFile(path.join(crlf.output,'reports',name),'utf8');const crlfName=`crlf-${name}`;const crlfFile=path.join(crlf.base,crlfName);await fs.writeFile(crlfFile,source.replace(/\r?\n/g,'\r\n'),'utf8');const table=`t${imported.length}`;const defs=Array.from({length:columns},(_,index)=>`c${index} TEXT`).join(',');const script=`DROP TABLE IF EXISTS ${table};CREATE TABLE ${table}(${defs});\n.mode csv\n.import --skip 1 ${crlfName} ${table}\nSELECT count(*) FROM ${table};`;const loaded=run(sqlite,[importDb],{input:script,cwd:crlf.base});assert(loaded.status===0,loaded.stderr||loaded.stdout);const count=Number(loaded.stdout.trim().split(/\r?\n/).at(-1));assert(count===records,`${name} CRLF import mismatch`);imported.push({file:name,records:count,columns});}await fs.rm(crlf.base,{recursive:true,force:true});

const version=run(sqlite,['--version']);assert(version.status===0,'SQLite version unavailable');console.log(JSON.stringify({result:'PASS',platform:process.platform,architecture:process.arch,node_version:process.version,sqlite_version:version.stdout.trim(),clean_directories:clean,valid_input_change:{changed_field:'sla_minutes.P2',from:priorP2,to:960,business_result_changed:true,assertions_passed:true},invalid_inputs:[{case:'missing_calendar',return_code:missingResult.status,no_residual_output:true},{case:'unfinished_sql',return_code:unfinishedResult.status,no_residual_output:true}],crlf_boundary:{sqlite_native_import:true,files:imported,extra_records:0},real_sqlite_executed:true},null,2));
